#!/usr/bin/python3
#
# Run the machine emulator and bootstrap into the "Program Input Routine".
#
# Usage: lgp21-run

import sys
import lgp21.machine as machine

with machine.Machine() as mach:
    mach.bootstrap()
    mach.run()
